### ISSUE TITLE
Allow for relations in glossary definitions.

### ISSUE THREAD

**Issue by jonsugar** [tightenco/onramp#101]
Adding relations to glossary definitions would make the Onramp user experience more seamless. By relations I mean "related terms" and "related resources".

- _Related terms_ would link to other terms within the glossary that have conceptual overlaps with the current term. 
- _Related resources_ would deep link the user to the appropriate onramp learning resources.

Using the term HTML as an example I'm proposing something similar to the following:

![Screenshot 2019-10-21 at 14 29 01](https://user-images.githubusercontent.com/1974648/67209389-2ab98980-f40f-11e9-8504-a72796208a94.png)

**Comment by mattstauffer** [comment]
uhhh that's friggin awesome

**Comment by jonsugar** [comment]
@mattstauffer Just for clarity that is a mockup image. I haven't coded anything yet. Was just proposing an Idea at this stage.

**Comment by mattstauffer** [comment]
Yep :)

**Comment by rontu85** [comment]
I just thought a bit about your idea. If we link from the glossary to the modules or the included learning resources why not do it the other way around. We could add the relevant glossary items to the modules pages. With this, a user could jump directly to the correct glossary item on the glossary page. Or we could even create a modal that displays the glossary text of the selected item.

**Comment by jonsugar** [comment]
Nice idea @rontu85!

**Comment by jonsugar** [comment]
@mattstauffer I am working on this.
