### ISSUE TITLE
Add PHP School

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/onramp#105]
https://www.phpschool.io/

**Comment by wotta** [comment]
Where do you want this to be added? Or should a new category be created?

**Comment by mattstauffer** [comment]
I'm not sure. I've never used it. It may just be a resource in the php module?

**Comment by wotta** [comment]
Sounds good, I will make a pr tonight to get this issue resolved.

**Comment by DominusKelvin** [comment]
Hey @wotta. Still working on this issue?

**Comment by wotta** [comment]
@DominusKelvin I already opened a PR. If more work is needed for this would love to know.

**Comment by DominusKelvin** [comment]
Alright @wotta. Great job

**Comment by DominusKelvin** [comment]
By the way. Can I get a link to the contribution guidelines?

**Comment by wotta** [comment]
@DominusKelvin I searched a bit for you but I couldn't find the contributing guidelines in the repository itself.
There is a draft version in one of the PR's. See link: https://github.com/tightenco/onramp/pull/91/files?short_path=cc4aac3#diff-cc4aac3e9be04e0413c9520f223b493c

I hope this helps you 🙂
