### ISSUE TITLE
Add a description to each module

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/onramp#106]
Reasoning: #53

**Comment by wotta** [comment]
Any ideas on how long the descriptions for each module should be?
Around the same length as the modules index page?

**Comment by mattstauffer** [comment]
Great question @wotta! The original suggestion in #53 was this:

> At this stage, you're probably thinking something along the lines of "i'd love to make the computer do something!". The problem is that shouldn't try to hack your way through it, you could, but there is a better way. Why instead of hacking and forcing, we can just ask the right questions to get propper information? Why instead of making the computer do something, we can ask for it, and get it. Enter the void of the main data driven declarative language, SQL (Structured Query Language) !

So.. probably longer than a varchar.

**Comment by wotta** [comment]
@mattstauffer Thanks for the answer. So to make sure I fully understand what you mean.
The quote you provided would act as the description for the SQL module.

**Comment by mattstauffer** [comment]
Right!

**Comment by wotta** [comment]
@mattstauffer do you happen to have any suggestions for the descriptions for the modules?
I really couldn't think of anything unfortunately.

**Comment by mattstauffer** [comment]
@wotta I'm ok if they're all left empty strings for now! We can add another task to actually write them :)

**Comment by wotta** [comment]
Thanks for the answer. I will check if I can help out with some other issue 🙂
