### ISSUE TITLE
Add a pseudo-contributing document

### ISSUE THREAD

**Issue by DaneEveritt** [tightenco/onramp#11]
Just giving this a look and thinking about what might be useful to add, I noticed there's not really a defined structure for _how_ things should be formatted. Bullet points, paragraphs, etc?

Otherwise looks like a very promising resource.

**Comment by mattstauffer** [comment]
For now, I think we'll do best to contribute in the simplest shape it's in: a title and links, and primarily keeping everything around the one file, `learn.php`:

https://github.com/tightenco/onramp/blob/master/learn.php

However, once we *figure out* more of the structure, I think that would be wise to have something, so it might be good to just create one now so we remember to update it later.
