### ISSUE TITLE
Ordering the list of available languages in the dropdown menu alphabetically

### ISSUE THREAD

**Issue by zk433** [tightenco/onramp#116]
I think the plan is to have the selected language determined by the user's locale? Or will it be English? Either way, I think the rest of the languages in the dropdown menu should be ordered alphabetically.

**Comment by mattstauffer** [comment]
I think it should be English at the top, and then alphabetical. That's only because the site will default to English, and all other languages will fall back to English.

Thoughts?

**Comment by zk433** [comment]
I think before the user select a language, then English should be at the top.

But once they select the preferred language, I think it should be at the top, as the selected language of the site.

**Comment by mattstauffer** [comment]
Agreed! That definitely makes the most sense. Let’s try it out. We *may* find It makes some aspects of the User experience feel weird but we won’t know until we try and it seems very reasonable.

**Comment by mattstauffer** [comment]
Closed by #118
