### ISSUE TITLE
Add some sort of toast notifications and update ResourceLanguagePreferenceSwitcher to use it for errors

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/onramp#130]

**Comment by sariyana** [comment]
Working on this one.

**Comment by mattstauffer** [comment]
https://github.com/euvl/vue-notification/

**Comment by mattstauffer** [comment]
Also, update language switcher to function like the resource language preference switcher functions, where it is an ajax call to preferences, after which the page changes. Unlike the pref switcher though it'll be forwarding to a new URL.
