### ISSUE TITLE
If user has resource language preference set in a cookie, save it as a preference in the wizard store method

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/onramp#136]

**Comment by rosswintle** [comment]
I popped in to have a look at this as @mattstauffer suggested people grab this issue in Telegram chat.

Firstly: is this change necessary? I couldn't find a path through the system that set a PREFERENCES::locale cookie prior to registration. The language switcher only links to the current page with a different locale.

#135 wants a change of language to be reflected in user preferences. This is fine if the user exists, but the user won't exist until they have got through the wizard. So why does the wizard need to save a preference based on a cookie that won't ever be set?

Are we expecting existing users to visit the wizard somehow? Or is there an outstanding issue to use cookies for users that aren't registered yet?

If this change is necessary then...

I've not been keeping up with all the live streams but decided to take a look. Initially I couldn't see what was required but then I dug in and realised what was needed. I think.

It looks like the "Wizard" is an extra step in the signup workflow that captures some preferences from the user. You can see the Wizard controller code in `app/Http/Controllers/Auth/WizardController.php`

The change here is - I think - to detect the `PREFERENCES::locale` cookie and save the locale from that cookie in `WizardController@store`

**Comment by rosswintle** [comment]
I did find an additional path through the site where a user registers but does not complete the wizard. They therefore have no preference set but they can re-visit the wizard (and it looks like #137 is trying to guide them back there).

You could theoretically do:

* Register
* DO NOT complete the Wizard
* Visit preferences page
* Visit wizard

A better fix would seem to be to somehow deny access to preferences until you've completed the wizard. That way you know you won't have a locale cookie set when you visit the wizard.

But maybe I've missed something. Sorry if I'm causing lots of confusion, or if I am just very confused myself.
2.

**Comment by jonsugar** [comment]
Having looked into this, I would take it one step further than ross. I think we should force logged in users to complete the wizard. 

The benefit of registering is to tailor the Onramp experience to the individual user. It doesn't make sense to me then that we have registered users that have not completed the wizard. A user in that state gains nothing from registering in my opinion. 

I suggest we:

1. introduce a middleware that redirects the user to the wizard if any preference specified as required in the WizardController validation is not stored in the database.
1. remove the 'Home', 'Learn', 'Glossary' and 'Preferences' links from the navigation bar to focus the user on completing the wizard.

In addition to providing a cleaner user experience, this approach has the advantage of ensuring the user preferences are always in a 'complete' state.

**Comment by rosswintle** [comment]
Yeah, as I finished writing this I felt that these two smaller technical changes (this and #135) were incomplete solutions to a broader user-flow problem; trying to fix some intermediate state that probably shouldn't exist.

I also wonder if we can simplify by having language in just one place: either the cookie or the user preferences. Do we really need it in both and the hassle of synchronising it? Perhaps this has been discussed elsewhere.

As Caleb Porzio would say: Make the change easy...make the easy change.

**Comment by jonsugar** [comment]
I think there is a use case for the cookie. It's Kina niche but... 

Let's say the user is just checking out the site, they have not registered yet then they switch the language. The cookie will allow them to come back at a later date with the language set.

Also, a user session expires they could still see the site in there chosen language when they return.

**Comment by rosswintle** [comment]
Oh yeah. Not saying don't use the cookie. I'm suggesting we don't have both the preference AND the cookie. I think the cookie should be the main way to track language choice.

If you had a preference set to "German" and, for some reason were logged out and using English, when you log in it would change to German. This would be weird, I think?

But maybe I've missed something about how the locales work.

**Comment by mattstauffer** [comment]
Some notes:

> As Caleb Porzio would say: Make the change easy...make the easy change.
That's Kent Beck :)

- Right, we're not saving it as a cookie, yet. We had planned to save it as a cookie so that if someone returns without signing up, they'd get the same language.
- We can avoid the cookie concept for the sake of this PR by just setting your language to whatever locale you're visiting the wizard with (check the URL)
- People can definitely exist without having gone through the wizard. I don't know that that is a huge problem.

> Are we expecting existing users to visit the wizard somehow?

Yep, there's a separate issue about this somewhere.

I think this can be very simple unless I'm missing something: when you complete the wizard, store the preferred language as whatever locale URL slug they just came from. Anything else can be tracked in separate issues.

**Comment by jonsugar** [comment]
>    * We can avoid the cookie concept for the sake of this PR by just setting your language to whatever locale you're visiting the wizard with (check the URL)

For clarity then, is the title of this issue misleading? It should be "Use the resource language locale part of the URL to pre-populate the wizzard form."

**Comment by jonsugar** [comment]
> I think this can be very simple unless I'm missing something: when you complete the wizard, store the preferred language as whatever locale URL slug they just came from. Anything else can be tracked in separate issues.

@mattstauffer I'm confused now. I went through the registration process on both Onramp prod and my local env (currently mes/install-nova ). In both cases the Prefered Language dropdown **is** pre-populated according to the locale part of the URL slug.

**Comment by rosswintle** [comment]
> People can definitely exist without having gone through the wizard. I don't know that that is a huge problem.

It adds in this additional user status (registered but not wizarded) that has to be handled in the user flow and tested. It seems, to me, to add some complexity.

> I think this can be very simple unless I'm missing something: when you complete the wizard, store the preferred language as whatever locale URL slug they just came from.

But the Wizard has a language selector?! We should store the value from that.

I don't think anything needs to be done here at all. The wizard uses the locale from the URL to set the selected option in the language dropdown. When the wizard is `store`ing it uses the dropdown value. I don't see why a cookie should override this.

**Comment by mattstauffer** [comment]
> I'm confused now. I went through the registration process on both Onramp prod and my local env (currently mes/install-nova ). In both cases the Prefered Language dropdown is pre-populated according to the locale part of the URL slug.

Yep. But that's because of your URL slug, not because of anything saved to your user.

> It adds in this additional user status (registered but not wizarded) that has to be handled in the user flow and tested. It seems, to me, to add some complexity.

Yep.. like I believe I've mentioned elsewhere, that was introduced when we added a wizard *after* users had already signed up, and can be solved by addressing this issue: https://github.com/tightenco/onramp/issues/137 , which is separate from the issue we're on right now.

> But the Wizard has a language selector?! We should store the value from that.

Oh... that wasn't a part of the original plans. HA. So this whole thing isn't super enecessary anyway. Cool. Done.
