### ISSUE TITLE
Add the translatable UI text from Resource Language Preference Switcher to various language JSON files

### ISSUE THREAD

**Issue by zuzana-kunckova** [tightenco/onramp#143]
We have made the UI text in the Resource Language Preference Switcher Vue component translatable, which means there are three more phrases that need adding and translating in the currently available translation files:

```
"All resources": "All resources",
":locale resources": ":locale resources",
"English and :locale resources": "English and :locale resources"
```

I will update the `cs.json` file.

The following files also need updating:

- [x] `da.json` (@sipman )
- [x] `cs.json` (zuzana)
- [x] `de.json` (@rontu85)
- [x] `id.json` (@rizkyarlin)
- [x] `pt-pt.json`(@joseborges) 
- [x] `sv.json` (@rockymontana) 

Thank you :)

**Comment by zuzana-kunckova** [comment]
I have added the czech translation, however, due to the way the Czech language works, the below is not grammaticaly correct: 
<img width="477" alt="Screenshot 2019-11-17 at 22 04 06" src="https://user-images.githubusercontent.com/15965102/69014979-66e8f700-0987-11ea-9495-2daa4999c64e.png">

I used a noun to state the name of the language (`Čeština`) but in order for this to be correct, an adjective `České zdroje` would have to be used. I know that pluralization is possible in Laravel, but how would that work in our case?

**Comment by mattstauffer** [comment]
@zuzana-kunckova Great question. What if you just don't use `:locale` for Czech? That might actually be fine.

**Comment by mattstauffer** [comment]
@sipman Hey, is updating these keys in `da.json` still something you're up to help with?

Thanks!

**Comment by sipman** [comment]
@mattstauffer Yes, sorry for my inactivity - I will look at it doing this week, hope thats acceptable ?

**Comment by mattstauffer** [comment]
@sipman Absolutely fine--no stress. Thanks!

**Comment by mattstauffer** [comment]
WOO WOO!!!
