### ISSUE TITLE
Language switcher fails for not-logged-in users with 422

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/onramp#154]
![image](https://user-images.githubusercontent.com/151829/71122944-a46fb880-21af-11ea-88c0-bc79108663a4.png)

**Comment by jonsugar** [comment]
Steps to reproduce:

1. Navigate to https://onramp.dev/en/modules
1. Click on any of the Recommended modules in the list.
1. Click on any of the links highlighted by the arrow below.
<img width="646" alt="Screenshot 2019-12-19 at 20 33 23" src="https://user-images.githubusercontent.com/1974648/71207600-24c11700-229f-11ea-9542-66dc7c92ed55.png">

**Comment by ktsubouchi** [comment]
It looks like there's a post request to `PreferenceController@store` from `ResourceLanguagePreferenceSwitcher.vue`, line 45.  The controller method validation requires `resource-language`, `locale` and `operating-system` but the payload sent by axios only has `resource-language`.

I'd be more than happy to create a pull request for this... would any of the following be appropriate?
- Add an edit method to PreferenceController.
- Add `locale` and `operating-system` to the axios request payload.  I believe `locale` can be accessed with `this.trans.locale` and for users who are not logged in, perhaps `operating-system` could have a default value.  For users who *are* logged in, can the preferences be loaded into the app.blade layout?
- Create a similar ResourceOsPreferenceSwitcher.

**Comment by Woddell** [comment]
I had said I would work on this on Telegram but I've been ill and never got round to it. I came to the same conclusion as @ktsubouchi. Unlikely I'll be able to look into it myself for a week or so.

**Comment by mattstauffer** [comment]
OK, thanks for the update on your availability @Woddell. And thanks for looking into it @ktsubouchi! I'll pick it back up then.

**Comment by mattstauffer** [comment]
Oops, I misread your note @ktsubouchi. I'd love for you to pick this up!

I think I'd probably want to just re-work that method so it's a patch instead of a post, and then we can rename it to update instead of store. Then we can drop the required on those fields, and only modify the preferences that were posted.

Let me know if that's not clear at all. Thanks!

**Comment by ktsubouchi** [comment]
Happy to help and that makes sense.
