### ISSUE TITLE
Laracasts content for Object-Oriented Programming

### ISSUE THREAD

**Issue by michapietsch** [tightenco/onramp#161]
https://laracasts.com/series/object-oriented-bootcamp-in-php is listed as free, but from lesson 2 on it's not. Also, as noted on Laracasts, this series is archived and recommends https://laracasts.com/series/object-oriented-principles-in-php

Maybe in addition from the Laracasts PHP section: https://laracasts.com/series/design-patterns-in-php and https://laracasts.com/series/solid-principles-in-php

**Comment by mattstauffer** [comment]
Ahhh--I didn't realize that. Thanks @michapietsch! I've updated the URL. I *think* (it's been a while) our current seeder doesn't even allow for differentiating paid vs free, but we're going to move all the data into Nova and a database very soon.
