### ISSUE TITLE
Update resources so that they can be assigned to more than one module.

### ISSUE THREAD

**Issue by TammyTee** [tightenco/onramp#185]

**Comment by TammyTee** [comment]
Not sure that this is a good idea (creating a many-to-many relationship)? The idea was that we should be able to easily add a resource to more than one module especially in cases where modules were being duplicated for WordPress. 

Closing this since I feel like that was a one time edge-case thing.

**Comment by mattstauffer** [comment]
Honestly I think you’re right. Gonna be a good number of shared resources.
