### ISSUE TITLE
Find (Potentially) a spot for this

### ISSUE THREAD

**Issue by devingray** [tightenco/onramp#191]
I found this whilst aimlessly scrolling through the Interwebs the other day https://andreasbm.github.io/web-skills/ 

I thought it could help in some way, some of the resources are straight copy paste from the web developer roadmap, but some may be useful here. 

Adding the issue for reference, feel free to close if not needed

**Comment by TammyTee** [comment]
Thanks @devingray! I'm going to go ahead and close this one out since it's likely this site may link to resources that we may already be referencing directly.
