### ISSUE TITLE
Nova out of date

### ISSUE THREAD

**Issue by LewisLarsen** [tightenco/onramp#208]
**Affected URL:** https://onramp.dev/nova/dashboards/main

**Description of problem:** Nova is reporting that it is out of date. This isn't a high priority as having checked the releases, there is nothing notable - mainly bug fixes and visual improvements. 

**Steps to resolve:** Update Laravel Nova.

**Screenshot:** ![Screenshot of Nova Dashboard](https://i.imgur.com/QGB7cJw.png)

**Comment by devingray** [comment]
Please check the PR for this https://github.com/tightenco/onramp/pull/210
