### ISSUE TITLE
Find a happy and healthy space for learning PHP

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/onramp#22]
I'm not sure the best way to learn PHP from scratch, but I'm very aware there's a lot of really not positive and really not modern PHP resources out there.

What's the best free way to learn PHP? And, if not free, what's the best single comprehensive paid resource (books, video tutes, online courses, etc.)?

Preferably answered by people who've actually done it recently, rather than those of us who've been writing PHP since the dinosaurs but have heard of a thing once (e.g. me lol)

**Comment by matt-allan** [comment]
I've heard good things about [PHP Pandas](https://daylerees.com/php-pandas/) by Dayle Reese. It's free and I think it would qualify as 'happy and healthy' :grin: 

[PHP School](https://www.phpschool.io/) seems like a good option if you are looking for something interactive.

**Comment by mattstauffer** [comment]
OO, didn't know PHP Pandas was free!
