### ISSUE TITLE
[Decision] What should we show for Resource completion percentages on Module cards?

### ISSUE THREAD

**Issue by TammyTee** [tightenco/onramp#229]
This question stemmed from wanting to know why some module cards showed **Resources 0%**. Decisions made here will likely be the case for quizzes and exercises once those are added.

| Scenario/Question | We Decided To ... / Decision |
|----|----|
| When a module has been completed | Hide the resource completion text |
| When a module has not been started/has no resource marked as completed | -- |
|Should paid resources be considered in the resource completion calculation? | -- |

**Comment by mattstauffer** [comment]
I think paid resources should not, even though that may prove to have some weird consequences later.

When they haven't started, maybe we could fix this problem with a label that makes it more clear?

<img width="374" alt="image" src="https://user-images.githubusercontent.com/151829/87726452-07005580-c78d-11ea-8177-1f4b6dc5b008.png">

This isn't quite right, but something like this?

```
<p class="mt-3 uppercase text-gray-600 font-semibold text-sm">My progress:</p>
```
