### ISSUE TITLE
Allow for a wizard up front?

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/onramp#24]
I'm imagining maybe this:

```
Welcome to Onramp!

Here are a few technologies that, if you're already familiar with, will impact the training we suggest. Choose as many as you need:

[HTML]
[CSS]
[Basic JavaScript]
[jQuery]
[WordPress implementation]
[WordPress plugin development]
[Git]
[Agile]

```

That's not an exhaustive list but it could be a good start. Then, when they choose them, we save it to their profile, and contextualize it.

Most of these options would just mean "don't show resources related to this because we assume they already know it." But at least WordPress would be a special case; that would *add* references designed specifically to help WP people transition.

**Comment by jonsugar** [comment]
Copied from [here](https://github.com/tightenco/onramp/issues/48#issuecomment-545830375) on an issue talking about tailoring Onramp resources based on the OS/Environment of the user.

>What if (like the language preference) the user can specify their preferred OS/Environment details Onramp can then tailor their experience.
>
>Maybe upon signup there is a wizard type widget that lets the user specify:
>
> 1. Their language.
> 1. Their appropriate track–"Brand-new developer", "Front-end developer" or "Wordpress developer".
> 1. What environment they are learning on-Linux, Mac or Windows.
>Of course the user will be able to change the preferences but I think that would be a good user >experience.
>
>Caveat here is that we would need a lot of content because we would need variants of all combinations >where appropriate but as a goal I think its reasonable.

**Comment by mattstauffer** [comment]
I think that's a really good idea.

**Comment by m50** [comment]
I'll take up this challenge. This sounds like a lot of fun to implement.

(just a note though: If I don't get it done by November 4th, someone else will need to pick it up)

**Comment by mattstauffer** [comment]
Also, I think I would change this original idea a *bit*... I think this was how I thought about it before the "tracks" idea. Maybe right now they just pick a track, pick a language, and pick an OS. Then we can explore whether we also let them pick topics they know already or not, like I mentioned in the first comment above.

Just FYI, you'll want to start by building the UI--In PR #103 I'll be done adding user preferences tooling so you can use that in the wizard to save their preferred OS and language. I *think* we had been imagining track being saved as a FK relationship on the user itself, as a track_id field?
