### ISSUE TITLE
Link all of the PHP Pandas sections

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/onramp#25]
https://daylerees.com/php-pandas/

**Comment by rockymontana** [comment]
I have glanced at this task so many times now.
I really like Dayle's way to write, but I'm really not sure where it would fit, except as a book resource connected to a skill. But we don't do resources under skills, right?

I think that could be valuable because there are many resources that has a broader perspective than the modules we are creating. It's the same thing with php the right way.

**Comment by mattstauffer** [comment]
@rockymontana Wouldn't sections like this: https://daylerees.com/php-pandas-functions/

Be good to add to the basic PHP section?

**Comment by rockymontana** [comment]
Most definitely!
We talked briefly about this a couple of days ago, but I’ll clarify my train of thoughts here. 

I think we see the skill feature somewhat differently and I think that’s the main thing we stumble upon when we’ve been talking about it.

I see a skill as a higher level content type than you do I think. I see it as something that you can visit aside from the modules and tracks. That’s how I justify it having it’s own sets of resources. That way I think we cover a wider audience (meaning those that likes learning by reading entire books).
By doing that (listing learnable skills) the user would also be able to see what kinds of skills are available and could work as an on-boarding mechanism.

Does that make sense?

**Comment by mattstauffer** [comment]
Hmm yah, I think "should resources attach to skills or only modules" should be a separate issue.

**Comment by TammyTee** [comment]
@mattstauffer do we want to link to each section individually as a resource? Or just link to the main site mentioned in your first comment?

**Comment by mattstauffer** [comment]
@TammyTee If the whole site fits in one module, it could be a single link. If not, we may need to link them all separately.

**Comment by TammyTee** [comment]
This has been added to the Beginning PHP module.
