### ISSUE TITLE
Write a description for the SQL and Databases Module

### ISSUE THREAD

**Issue by TammyTee** [tightenco/onramp#251]
@mattstauffer Let me know if this is good or if you have suggestions:

Learn to store, query, and manipulate your application's data using SQL.

**Comment by andrewmile** [comment]
@TammyTee I think what you have here is good although I changed `manipulate` to `modify`.  I went ahead and updated it in Nova.

**Comment by TammyTee** [comment]
Thanks @andrewmile!
