### ISSUE TITLE
Link to Codecademy?

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/onramp#27]
https://www.codecademy.com/learn/learn-php
https://www.codecademy.com/learn/learn-html
https://www.codecademy.com/learn/learn-css
https://www.codecademy.com/learn/learn-javascript
https://www.codecademy.com/learn/make-a-website

Never used this site. Is it good? Any other things?

**Comment by jase-languasco** [comment]
I think codecademy is a great resource. It takes a different approach to teach the material and is mostly hands-on as opposed to video tutorials, which can be a nice change of pace for the learner.

**Comment by jase-languasco** [comment]
- I created a PR if you decide to move forward with Codecademy -- https://github.com/tightenco/onramp/pull/29. 
- I didn't add the last link to "make a website" because it breaks the current list structure and includes HTML and CSS.

**Comment by TammyTee** [comment]
Closing as these were already added as resources in Onramp under the "Build a basic website" track as a part of #29.
