### ISSUE TITLE
Misplaced free v. paid link.

### ISSUE THREAD

**Issue by MacelinCane** [tightenco/onramp#273]
Hi. Loving this strategy, and its content. I just found something that maybe changed since it was plugged in.
The one listing in the free resources tab on this page is no longer free. 
https://onramp.dev/en/modules/object-oriented-programming/free-resources
And the listing in the Paid resources tab, is free. 
https://onramp.dev/en/modules/object-oriented-programming/paid-resources
Maybe they got flipflopped. 

That's it. 
Thanks for all the work. 
Hoping to contribute when I get a little further. 
Chris

**Comment by mattstauffer** [comment]
Fixed. Thanks Chris!
