### ISSUE TITLE
Link to General Assembly Dash?

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/onramp#28]
https://dash.generalassemb.ly/

**Comment by darkboywonder** [comment]
I played around with it this morning, and I like the guidance. I would link this. I feel we can break the usage of this up into segments wrapped around other tidbits of information that give more background about the DOM and general structure. An example would be explaining doctype or head vs. body tags as this seems to jump straight into building a website and using tags.

**Comment by rockymontana** [comment]
I thought GA was referring to Google Analytics. Made me shrug hehe.
Might be a good idea to clarify in case people are searching for issues?

**Comment by TammyTee** [comment]
Moved to Nova.
