### ISSUE TITLE
Figure out where https://phptherightway.com/ fits

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/onramp#34]

**Comment by TammyTee** [comment]
@mattstauffer This resource is offered in multiple languages. Do we want to add this as a separate resource for each of the languages that Onramp supports?

![image](https://user-images.githubusercontent.com/8689444/86259022-8127bc00-bb89-11ea-9f67-69eeedfcb2d5.png)

**Comment by mattstauffer** [comment]
Hmmmmmm that's a very good question.

I guess so? I'm a bit nervous of what this will do to anyone who picks "all languages" but I think that's not our preferred view anyway..so.. hopefully that's ok?

**Comment by TammyTee** [comment]
@mattstauffer hmm, yes that is a good point .... well if we just added the English version, they could then select their preferred language on the "PHP: The Right Way" site itself.

**Comment by mattstauffer** [comment]
@TammyTee Right.. unless the person had chosen something like "Spanish" and then they set it to only show their locale. They would never know this *had* a Spanish translation.

I think let's prioritize for people doing one of the following settings, in this order:

- English only
- My language only
- My language and English

So, for that reason, I think we want to add it in all languages.

Thanks Tammy! Let me know if you need any help from me to do this!

**Comment by TammyTee** [comment]
**Onramp supported:** 
English - https://phptherightway.com/
Bahasa - http://id.phptherightway.com/
Portugues - http://br.phptherightway.com/
Spanish - https://phpdevenezuela.github.io/php-the-right-way/
French - https://eilgin.github.io/php-the-right-way/
