### ISSUE TITLE
People don't buy what you do, they buy why you do it.

### ISSUE THREAD

**Issue by nicorafales** [tightenco/onramp#53]
[(sic) Simon Sinek.](https://www.ted.com/talks/simon_sinek_how_great_leaders_inspire_action)

We need to let them know why we (as a more experience programmers) think they should complete this specific skill, at this specific stage. And we need to freshen up the idea of why we think this or that is important, and how it changed our lifes when we learned it.

This could become a UI/UX problem but never the less, keeping this in mind might be of use.
We should add an overview (with a tooltip or something more powerful, like media content of our own).
I think this should be added meta-content made from anyone who adds the contribution. This makes this site different from any wiki guide and reflects upon the mission and vision of this app.

for example, when (if) we add the section of SQL tutorial  (#52 ), we explain why we think it would be beneficial, with something like:

> At this stage, you're probably thinking something along the lines of "i'd love to make the computer do something!". The problem is that shouldn't try to hack your way through it, you could, but there is a better way. Why instead of hacking and forcing, we can just ask the right questions to get propper information? Why instead of making the computer do something, we can ask for it, and get it. Enter the void of the main data driven declarative language, SQL (Structured Query Language) !

😊

**Comment by mattstauffer** [comment]
Closed; added an issue about how to implement this that's more concrete, #106. Thanks!
