### ISSUE TITLE
Add Laravel Daily courses

### ISSUE THREAD

**Issue by zuzana-kunckova** [tightenco/onramp#59]
https://laraveldaily.teachable.com/

A paid content, but I think Povilas's content is good quality. He posts a lot of live-coding sessions on YouTube too, you can check out his teaching style there (for example this video: https://www.youtube.com/watch?v=YUUokBJyJzw).
He has a website full of Laravel tutorials and tips: https://laraveldaily.com/.

**Comment by mattstauffer** [comment]
Once we move to database-backed, we can add this to the paid section. Thanks!

**Comment by TammyTee** [comment]
Moved to Nova.
