### ISSUE TITLE
[Suggestion] Do not separate resources by languages

### ISSUE THREAD

**Issue by eduarguz** [tightenco/onramp#63]
Hi Matt.
I have a suggestion to do... 

__I think that onramp should not separate the resources by language.__

When I first saw that you were adding language support to onramp, I tought that it was only a site content translation, and I think it is very nice, but I dont think that onramp should separate the resources by language. 

It is not very clear that the resources when working on `es` are different than the resources when working on `en`. My main language is Spanish but I can properly understand resources in English, and many people can too... and that makes both of these resources useful for my learning. I think these resources should remain together or at least `tagged` or `categorized` but still in the same page view.

Just a suggestion 😇
Thank you so much...

**Comment by mattstauffer** [comment]
Thanks! This is a super interesting idea and I've love to learn and think more about this.

**Comment by Treggats** [comment]
adding to this idea, we can have a default learn.php which defaults to english titles, but with an extra key you can add titles in different languages.

@mattstauffer should I open a draft PR to show my idea?

**Comment by rockymontana** [comment]
Shouldn’t we use the spatie package for this as well? Making the resource title and link translatable should sort it out, right?

**Comment by rockymontana** [comment]
Shouldn’t we use the spatie package for this as well? Making the resource title and link translatable should sort it out, right?

Edit: Sorry, wrong issue, I believe.

**Comment by rontu85** [comment]
We are already creating user accounts/profiles here. I thought it would be nice if a user can select, which languages he speaks. This would result in a list of resources in English (as default for everyone) and in addition the resources which are in the languages a user defines in his profile (e.g. Spanish and Portuguese). For this to work for all resources must be tagged with its respective language.

**Comment by jonsugar** [comment]
I had a slightly different idea but it achieves the same thing. I was thinking about a widget/filter near the locale switcher that allows the user to "Only show resources in selected language", "Only show resources in selected language and English" and "Show all resources". It would require the same tagging of resources as mentioned above, just a different way of doing the same thing.

**Comment by jonsugar** [comment]
@mattstauffer Potentially, I will start working on this then after my PR #78 is (hopefully) accepted. Unless somebody else wants to tackle it.

Alternatively, this could be a self contained piece of work to do on stream?

**Comment by mattstauffer** [comment]
@jonsugar that might be a good stream topic for tomorrow... assuming i can get all the rest of the stuff we have pending merged. Let me get to that!

**Comment by TammyTee** [comment]
Closing as this was resolved as a part of #78.
