### ISSUE TITLE
Update mes/database-backed-learning seeders to match learn.en.php and learn.es.php

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/onramp#64]

**Comment by vmitchell85** [comment]
@mattstauffer While working on this we discovered a few "issues" that should probably be decided on before we can finish this out:

- Module Children exist in current learn files (Local PHP Environment > Valet (if using a Mac)), how should we handle those?
- Should there be Language specific Modules or just language specific resources, how should we indicate a resource is in a specific language? There is no column for it currently. I was thinking maybe storing the name in a json column with multiple translations similar to Spatie's Laravel Tags package does?


For anyone interested it was streamed live on [twitch](https://www.twitch.tv/vmitchell85) and the video should be available [here](https://www.twitch.tv/vmitchell85/videos).

**Comment by mattstauffer** [comment]
Thanks!

- The current learn.en.php has almost all modules... HTML/CSS/terminal/git can be in a single module called "Build a basic web site" or something similar. I think you can see me doing this in the database seeder.
- Language specific resources, definitely not modules. Great question on how to handle translations. We might have to talk that over live on the next stream.. there's a similar conversation happening on #66
