### ISSUE TITLE
Question and suggestion: which markdown

### ISSUE THREAD

**Issue by cameron-elliott** [tightenco/onramp#72]
Hey  Tighten, this is a cool project of yours I just discovered.

One thing I have been floundering around, is trying to figure out which markdown
you guys are running in Jigsaw.
Is it the Commonmark markdown?
Maybe this page should have a comment regarding which markdown is available??

Also, maybe a link on the onramp page would be helpful for those new to markdown.

Sorry if I am suggesting too much.

**Comment by mattstauffer** [comment]
Hey Cameron!

Onramp isn't in Jigsaw anymore, so I don't know how much Markdown it uses, if any at all. :)

The question about Jigsaw's Markdown processor would probably be best left on the Jigsaw repo, where I'm sure Keith would be happy to clarify, although just from glancing at the composer.json there it seems like it's running Parsedown Extra, which can get you part of the way to the answer to your question.

Thanks for the kind words!

**Comment by cameron-elliott** [comment]
Thanks, Matt
