### ISSUE TITLE
readme.md and contributing.md could include more info about getting started

### ISSUE THREAD

**Issue by rosswintle** [tightenco/onramp#80]
There was chat elsewhere today about things like:

* What is on different branches of this repo?
* How PR's work
* Which livestream videos should I watch? All of them? The latest?
* Details of the database seeding

And I have my own questions about exactly what this repo is and if/how I can contribute.

I'll copy some conversation below for reference.

My reaction was to pop in here and see what the readme and contrinuting.md say, and that lead me to opening this issue to try and improve those documents.

@mattstauffer said: 

> one of the things i think would be really cool is if we can make this not only super easy for new folks to use, but also super easy for them to contribute to, AND we can maybe even use it and its readme/contributing.md/etc. as examples of how to make open source laravel projects friendly to new folks

So let's do that. I'll try and start making some improvements to the docs over the next couple of days. But feel free to chip in if I can't.

## Relevant extracts/questions

> How do the migrations/seeding work?

`php artisan migrate:fresh —seed`

> What IS the mes/database-backed-learning branch? Which should I use if contributing?

??? - need a general overview of branches - presumably this is explained in the videos?

> How do PR's work with merging? (This started as a question along the lines of: "If I fork the repo and work on the master, then create a PR with my changes, won't it create conflicts if it's merged after other changes on master?")

Probably need to point off to another resource on "How to PR with Git/GitHub". This is old and JavaScripty, but may be a helpful 38 mins of free (I think!) video: https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github

**Comment by Treggats** [comment]
Hi @rosswintle In regard to your questions;

Usually when contributing to a project, branches are branched of master or the latest version. What is best in this case is for @mattstauffer to decide.

How PR's work and how to keep your branch up to date is something I would be willing to write in the contributing guide. Let me know if I should PR this.

Github also has a [Youtube playlist](https://www.youtube.com/watch?v=FyfwLX4HAxM&list=PLg7s6cbtAD15G8lNyoaYDuKZSKyJrgwB-) which explains git

**Comment by Treggats** [comment]
talked to Matt, I'm going to PR the pull request flow which will include the egghead video

**Comment by mattstauffer** [comment]
With regard to branches, the `mes` branch is going away ASAP and then we'll be onto a normal feature-branches-off-of-master flow. We may later add a develop branch for staging but not at the moment.

Y'all let me know what you'd like me to write up and I'll be happy to answer any specific questions or write anything up!

**Comment by mattstauffer** [comment]
https://tighten.co/blog/building-a-great-pull-request/

https://chris.beams.io/posts/git-commit/
