### ISSUE TITLE
What I'm working on

### ISSUE THREAD

**Issue by jonsugar** [tightenco/onramp#86]
While we do not have permissions to assign and tag issues on the Onramp repo, we can track what we are working on in this Issue.

- Please add only one comment and list the things you are working on.
- Please add issue # links to identify the work if an issue exists.
- Add your tag/name on telegram in the comment so we can ask questions in Telegram if needed.
- Please don't ask questions or comment directly in this issue. Use telegram or comment directly in the issue.

**Please delete your comment when not working on anything.**

**Comment by jonsugar** [comment]
**jonsugar** on Telegram

- I am adding a seeder for glossary terms.

**Comment by Treggats** [comment]
Treggats on telegram

* create/expand the contributing document

**Comment by zk433** [comment]
Zuzana on Telegram

- I am fixing the broken footer layout on mobile - issue #88

**Comment by jonsugar** [comment]
**jonsugar** on Telegram

- I am working on Issue #95 - Fix confusing module language filter on the module page.

**Comment by rontu85** [comment]
**tobias_etzold** on Telegram

- I am working on Issue [#96](https://github.com/tightenco/onramp/issues/96) - Merge the two table of contents of the glossary into one

**Comment by jonsugar** [comment]
**jonsugar** on Telegram

- I am working on Issue #99–Upgrade to Laravel version 6.

**Comment by jonsugar** [comment]
**jonsugar** on Telegram

- I am working on issue #101 - Allow for relations in glossary terms.

**Comment by mattstauffer** [comment]
If y'all are working on something, please also comment on the individual issue so I can assign it to you. Thanks!

**Comment by m50** [comment]
**Marisa Clardy** on Telegram
Just starting work on Issue #24.

**Comment by zk433** [comment]
Zuzana on Telegram

I'm starting to work on translating all the pagination, validation and authentication text to the Czech language.

Issue #114
